# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrwndMcp < Formula
  desc "Grwnd MCP CLI for Claude Desktop integration"
  homepage "https://grwnd.ai"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Grwnd-AI/grwnd-mcp/releases/download/v0.1.0/grwnd-mcp_0.1.0_darwin_amd64.tar.gz"
      sha256 "460f3eebfea34daae7dc22ebb40415b08e2452b8aeec21591c7842546216fe37"

      def install
        bin.install "grwnd-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Grwnd-AI/grwnd-mcp/releases/download/v0.1.0/grwnd-mcp_0.1.0_darwin_arm64.tar.gz"
      sha256 "407282abf5c6c9c02d28bc0f8105c3abd525b0f3f08edb1353af49b3d949dd6e"

      def install
        bin.install "grwnd-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Grwnd-AI/grwnd-mcp/releases/download/v0.1.0/grwnd-mcp_0.1.0_linux_amd64.tar.gz"
      sha256 "2c9c5d0459f7e16710f04df18ef8df2191de80d85aaa3e69a86d6abd2a7046e7"
      def install
        bin.install "grwnd-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Grwnd-AI/grwnd-mcp/releases/download/v0.1.0/grwnd-mcp_0.1.0_linux_arm64.tar.gz"
      sha256 "b4196ebcf6790ac2d9958d495e6de0e4554d8cfc3ec3d89d51f5ab4b3b3bb5ca"
      def install
        bin.install "grwnd-mcp"
      end
    end
  end

  test do
    system "#{bin}/grwnd-mcp", "version"
  end
end
