# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrwndMcp < Formula
  desc "Grwnd MCP CLI for Claude Desktop integration"
  homepage "https://grwnd.ai"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Grwnd-AI/grwnd-mcp/releases/download/v0.2.0/grwnd-mcp_darwin_amd64.tar.gz"
      sha256 "b1693d886cf7595268c46c5f5440213ede64bf05b8e5f7c100d9e596e50e3c3c"

      def install
        bin.install "grwnd-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Grwnd-AI/grwnd-mcp/releases/download/v0.2.0/grwnd-mcp_darwin_arm64.tar.gz"
      sha256 "887dadcb8c9dad564b10bca71a0c63ef71c258f236ea232a2b41aff3e01f0801"

      def install
        bin.install "grwnd-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Grwnd-AI/grwnd-mcp/releases/download/v0.2.0/grwnd-mcp_linux_amd64.tar.gz"
      sha256 "c30c8d18600048c1e23093b95c62635c27fd981c0180e9c725b80c83c22f2ebb"
      def install
        bin.install "grwnd-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Grwnd-AI/grwnd-mcp/releases/download/v0.2.0/grwnd-mcp_linux_arm64.tar.gz"
      sha256 "177e990eb24a677b4e7dcd2f1f5b131430daa76a801b355d3a91a03e9a69747e"
      def install
        bin.install "grwnd-mcp"
      end
    end
  end

  test do
    system "#{bin}/grwnd-mcp", "version"
  end
end
