# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrwndMcp < Formula
  desc "Grwnd MCP CLI for Claude Desktop integration"
  homepage "https://grwnd.ai"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Grwnd-AI/grwnd-mcp/releases/download/v0.2.0/grwnd-mcp_darwin_amd64.tar.gz"
      sha256 "79ba0e6434687fd0255d0831a03871df13dd2f8d7ec4ae94cbdc0acc410286c4"

      def install
        bin.install "grwnd-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Grwnd-AI/grwnd-mcp/releases/download/v0.2.0/grwnd-mcp_darwin_arm64.tar.gz"
      sha256 "31fc5bfbfcb0c574ef9e1b4349c4dc70821e89df4e3ed7d7877fd2eb4049688e"

      def install
        bin.install "grwnd-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Grwnd-AI/grwnd-mcp/releases/download/v0.2.0/grwnd-mcp_linux_amd64.tar.gz"
      sha256 "e62a76c2ac7328c8a986caaea41d21bc15ae50e33b182f20e376587658c43326"
      def install
        bin.install "grwnd-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Grwnd-AI/grwnd-mcp/releases/download/v0.2.0/grwnd-mcp_linux_arm64.tar.gz"
      sha256 "4f3a0afd4f356056e89f3724bc8e63689422a0df7a1f851fcab85c83683f52e6"
      def install
        bin.install "grwnd-mcp"
      end
    end
  end

  test do
    system "#{bin}/grwnd-mcp", "version"
  end
end
